export const GET_PRODUCTS = 'GET_PRODUCTS'
export const RESET_PRODUCTS = 'RESET_PRODUCTS'
export const GET_ORDERS = 'GET_ORDERS'
export const ADD_ORDER = 'ADD_ORDER'
export const CHANGE_JUMLAH = 'CHANGE_JUMLAH'
export const SORT_BY_DATE = 'SORT_BY_DATE'
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT'
